PANDAS

In [29]:
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Mouse', 'Monitor'],
    'Price': [1200, 25, None, 75, 25, 150],
    'Stock': [5, 50, 10, None, 50, 8],
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Electronics']
}

banana = pd.DataFrame(data)
# banana=pd.read_csv("C:\\Users\\HP\\Downloads\\global_natural_disasters_2000_2025.csv")
print(banana.head())
print("--------------------------------------------------------------")
print(banana.tail())
print("--------------------------------------------------------------")
print(banana.info())
print("--------------------------------------------------------------")
print(banana.describe())
print("--------------------------------------------------------------")
print(banana.columns)
print("--------------------------------------------------------------")
print(banana.shape)
print("--------------------------------------------------------------")
print(banana.isnull().sum())
print("--------------------------------------------------------------")
print(banana.dropna(inplace=True))
print("--------------------------------------------------------------")
banana['Price'] = banana['Price'].fillna(banana['Price'].mean())
print(banana)
print("--------------------------------------------------------------")
high_price = banana[banana['Price'] > 100] 
print(high_price)

    Product   Price  Stock     Category
0    Laptop  1200.0    5.0  Electronics
1     Mouse    25.0   50.0  Accessories
2   Monitor     NaN   10.0  Electronics
3  Keyboard    75.0    NaN  Accessories
4     Mouse    25.0   50.0  Accessories
--------------------------------------------------------------
    Product  Price  Stock     Category
1     Mouse   25.0   50.0  Accessories
2   Monitor    NaN   10.0  Electronics
3  Keyboard   75.0    NaN  Accessories
4     Mouse   25.0   50.0  Accessories
5   Monitor  150.0    8.0  Electronics
--------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Product   6 non-null      str    
 1   Price     5 non-null      float64
 2   Stock     5 non-null      float64
 3   Category  6 non-null      str    
dtypes: float64(2), str(2)
memory usage: 324.0 bytes
None
-------------------

NUMPY

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Shape: {arr2d.shape}")   
print(f"Dims:  {arr2d.ndim}")    
print(f"Type:  {arr2d.dtype}")   
print(f"Size:  {arr2d.size}")   


# Math operations
print(arr1d + 10)  
print(arr1d * 2)   

# Statistics
print(np.mean(arr1d))  
print(np.median(arr1d)) 
print(np.std(arr1d))    
print(np.sum(arr2d, axis=0))  



print(arr2d[0, 1:3])

# Turn our 6-element 1D array into a 3x2 2D array
reshaped = arr1d.reshape(3, 2)
print(reshaped)

row_adder = np.array([10, 20, 30])
result = arr2d + row_adder
print(result)

Shape: (2, 3)
Dims:  2
Type:  int64
Size:  6
[11 12 13 14 15 16]
[ 2  4  6  8 10 12]
3.5
3.5
1.707825127659933
[5 7 9]
[2 3]
[[1 2]
 [3 4]
 [5 6]]
[[11 22 33]
 [14 25 36]]


PYSPARK

In [ ]:
import pandas as pd
import os
os.environ["JAVA_HOME"]   = r"C:\Program Files\Java\jdk-17"
os.environ["HADOOP_HOME"] = r"C:\hadoop"
os.environ["PATH"] = r"C:\Program Files\Java\jdk-17\bin;" + os.environ["PATH"]
os.environ["PYSPARK_PYTHON"] = r"c:\Git\.venv\Scripts\python.exe"

# Remove SPARK_HOME completely
if "SPARK_HOME" in os.environ:
    del os.environ["SPARK_HOME"]

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg

spark = SparkSession.builder \
    .master("local[2]") \
    .appName("bigdata") \
    .config("spark.driver.host", "127.0.0.1") \
    .config("spark.driver.bindAddress", "127.0.0.1") \
    .getOrCreate()

print("Ready:", spark.version)

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Mouse', 'Monitor'],
    'Price': [1200, 25, None, 75, 25, 150],
    'Stock': [5, 50, 10, None, 50, 8],
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Electronics']
}

df = pd.DataFrame(data)
spark_df = spark.createDataFrame(df)
spark_df.show()
spark_df.select("Product", "Price").show()
spark_df.filter(spark_df.Price > 100).show()
spark_df.groupBy("Category").count().show()

print("---------------------------------------------------------------")
spark_df.printSchema()


print("---------------------------------------------------------------")
# 4. Register as a SQL Temporary View
spark_df.createOrReplaceTempView("store")

# 5. Execute SQL Queries
print("--- Full Dataset ---")
spark.sql("SELECT * FROM store").show()

print("--- Total Inventory Value per Category ---")
spark.sql("""
    SELECT Category, SUM(Price * Stock) as Total_Value 
    FROM store 
    WHERE Price IS NOT NULL AND Stock IS NOT NULL 
    GROUP BY Category
""").show()

print("--- Products with Stock < 10 ---")
spark.sql("SELECT Product, Stock FROM store WHERE Stock < 10").show()

print("--- Average Price of Unique Products ---")
spark.sql("SELECT AVG(DISTINCT Price) as Avg_Unique_Price FROM store").show()




# PySpark is essential for big data because it processes massive datasets in parallel across a cluster of computers using In-Memory computing, making it significantly faster than traditional disk-based systems. It allows developers to use Python's simple syntax to scale data processing from a single laptop to petabytes of data seamlessly.

Ready: 4.1.1
+--------+------+-----+-----------+
| Product| Price|Stock|   Category|
+--------+------+-----+-----------+
|  Laptop|1200.0|  5.0|Electronics|
|   Mouse|  25.0| 50.0|Accessories|
| Monitor|   NaN| 10.0|Electronics|
|Keyboard|  75.0|  NaN|Accessories|
|   Mouse|  25.0| 50.0|Accessories|
| Monitor| 150.0|  8.0|Electronics|
+--------+------+-----+-----------+

+--------+------+
| Product| Price|
+--------+------+
|  Laptop|1200.0|
|   Mouse|  25.0|
| Monitor|   NaN|
|Keyboard|  75.0|
|   Mouse|  25.0|
| Monitor| 150.0|
+--------+------+

+-------+------+-----+-----------+
|Product| Price|Stock|   Category|
+-------+------+-----+-----------+
| Laptop|1200.0|  5.0|Electronics|
|Monitor|   NaN| 10.0|Electronics|
|Monitor| 150.0|  8.0|Electronics|
+-------+------+-----+-----------+

+-----------+-----+
|   Category|count|
+-----------+-----+
|Electronics|    3|
|Accessories|    3|
+-----------+-----+

---------------------------------------------------------------
root
 |-- Prod

MATPLOTLIB